### PR TITLE
process: allow outgoing channel not found for failed htlcs

### LINKED ISSUE #97: crash with "channel not found" for "UnknownNextPeer" routing failures
Circuitbreaker crashed, this is in the logs:

```
Nov 23 13:32:57 server circuitbreaker[2023854]: 2023-11-23T13:32:57.933+0100        ERROR        Unexpected exit        {"err": "channel not found: 733007018886561798"}
Nov 23 13:32:57 server circuitbreaker[2023854]: main.main
Nov 23 13:32:57 server circuitbreaker[2023854]:         /home/cotto/IdeaProjects/circuitbreaker/main.go:144
Nov 23 13:32:57 server circuitbreaker[2023854]: runtime.main
Nov 23 13:32:57 server circuitbreaker[2023854]:         /home/cotto/go/src/runtime/proc.go:250
```

Neither my own tools nor amboss.space has anything to say about that channel ID. I don't know where it comes from.

### PR DESCRIPTION
**Pull request by carlaKC**
Fixes #97 

Update process to log channel not found errors for failed lookup of outgoing HTLCs for payments that failed. For incoming links, we know that the channel exists because something was forwarded to us over an existing channel, but this level of validation has not yet occurred for the outgoing link (as we intercept it before checking that the channel exists) so it's possible that we can't lookup the bogus channel. 

Change: 
* Just log failed + outgoing channel not found htlcs errors
  * This will store an empty pubkey for the outgoing peer, I think that's worth storing because it can easily be filtered
* Still enforce channel lookup for successful HTLCs, as we know the channel exists

### CODE REVIEW

File: process_test.go [hunk 1]
```diff
@@ -408,6 +408,115 @@ func TestChannelNotFound(t *testing.T) {
...
+
+	p := NewProcess(client, log, cfg, db)
+
+	resolved := make(chan struct{})
+	p.resolvedCallback = func() {
+		close(resolved)
+	}
+
+	exit := make(chan error)
+	go func() {
```
Comment (joostjager) [inline process_test.go:477]: There is quite a bit of duplication of setup code across the various tests. Non-blocking.

File: process.go [hunk 2]
```diff
@@ -337,18 +337,35 @@ func (p *process) eventLoop(ctx context.Context, group *errgroup.Group) error {
...
+			// resolved event. Here we handle a channel lookup error
+			// differently to the incoming channel, because it's possible
+			// we were forwarded a HTLC with a bogus outgoing channel. If
+			// this is the case, LND would have failed the HTLC back even if
+			// we let it through. We catch and log that error, rather than
+			// exiting like we do with incoming channels (where we reasonably
+			// expect to find the channel). We still enforce channel lookup
+			// for successful HTLCs, because then we know that the channel
+			// does exist and should be found.
+			var outgoingPeer route.Vertex
```
Comment (joostjager) [inline process.go:350]: Instead of an all-zeroes key in the database, a NULL value would be cleaner I think.

**Review by joostjager — COMMENTED** [review]
I also didn't think about this case. Did the bug already go out on umbrel?

File: process_test.go [hunk 3]
```diff
@@ -408,6 +408,115 @@ func TestChannelNotFound(t *testing.T) {
...
+		{
+			name:          "outgoing found, not settled",
+			settled:       false,
+			outgoingFound: true,
+		},
+		{
+			name:          "outgoing not found, settled",
+			settled:       true,
+			outgoingFound: false,
+			err:           errChannelNotFound,
```
[the remark this answers is not in the document]
Comment (carlaKC) [reply process_test.go:436]: Yes we still don't account for pending channels because the pending API doesn't surface all the info we need. 

This has always existed for the incoming channel and it doesn't seem like anybody has run into issues? But we could downgrade to just log whenever channel is not found to be cautious?

**Comment by carlaKC** [comment]
> Did the bug already go out on umbrel?

Sadly yes, I'll tag a new release + update once this is in.

File: process.go (hunk 2 above)
Comment (carlaKC) [reply process.go:350]: Happy for me to add a migration to relax the not-null restriction on `outgoing_peer` to do this?

File: process_test.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (joostjager) [reply process_test.go:436]: That was also what I thought. But agreed that it seems far off the hot path. Whatever you think is best.

File: process.go (hunk 2 above)
Comment (joostjager) [reply process.go:350]: An alternative would be to just not record anything in the fwd log at all in these cases?

**Comment by carlaKC** [comment]
Sorry for the delay on this - running out of capacity with the end of year approaching. Decided to just log + skip recording the HTLC for the sake of getting a fix out before the holidays. Can always come back and do the DB update at a later stage with minimal code churn.

File: peer_controller.go [hunk 4]
```diff
@@ -433,6 +433,18 @@ func (p *peerController) markHtlcComplete(ctx context.Context, key circuitKey,
 		return
 	}
 
+	// If we couldn't look up an outgoing peer for the HTLC, either:
+	// 1. The outgoing channel never existed (since this is not validated on intercept)
+	// 2. The outgoing channel is pending close at time of resolution (edge case)
+	//
+	// Log and skip this HTLC for now to avoid adding empty values to the DB.
+	if resolution.outgoingPeer == nil {
+		log.Debugf("HTLC: %v has no known outgoing peer, not storing resolution",
```
Comment (joostjager) [inline peer_controller.go:442]: Are there always two log lines now for this case?

**Review by joostjager — COMMENTED** [review]
I am fine with postponing the db migration.

File: peer_controller.go (hunk 4 above)
Comment (carlaKC) [reply peer_controller.go]: Ah yes there are, cutting this one.

**Review by joostjager — APPROVED** [review]
